# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/search-papers',
                'doc_host': 'https://deven367.github.io',
                'git_url': 'https://github.com/deven367/search-papers',
                'lib_path': 'search_papers'},
  'syms': { 'search_papers.search': { 'search_papers.search._fitler_null_authors': ( 'search.html#_fitler_null_authors',
                                                                                     'search_papers/search.py'),
                                      'search_papers.search._process_response': ( 'search.html#_process_response',
                                                                                  'search_papers/search.py'),
                                      'search_papers.search.search': ('search.html#search', 'search_papers/search.py')},
            'search_papers.utils': {'search_papers.utils.set_api_key': ('utils.html#set_api_key', 'search_papers/utils.py')}}}
