# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/search-papers',
                'doc_host': 'https://deven367.github.io',
                'git_url': 'https://github.com/deven367/search-papers',
                'lib_path': 'search_papers'},
  'syms': {'search_papers.core': {'search_papers.core.foo': ('core.html#foo', 'search_papers/core.py')}}}
