# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['set_api_key']

# %% ../nbs/00_utils.ipynb 2
import os
from fastcore.script import call_parse

# %% ../nbs/00_utils.ipynb 3
@call_parse
def set_api_key(api_key:str)->None:
    """
    Set the API key to be used for the requests
    """

    # write the API key to .elsevier_api_key in the home directory
    with open(os.path.expanduser('~/.elsevier_api_key'), 'w') as f:
        f.write(api_key)

    os.environ['ELSEVIER_API_KEY'] = api_key
    print('API key set successfully')

